-- MySQL Script generated by MySQL Workbench
-- Mon Apr 18 12:40:22 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pizzasevice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzaservice` ;

-- -----------------------------------------------------
-- Schema pizzasevice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaservice` DEFAULT CHARACTER SET utf8 ;
USE `pizzasevice` ;

-- -----------------------------------------------------
-- Table `pizzasevice`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaservice`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `pizzaservice`.`pizzas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pizza_name` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `pizza_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pizzasevice`.`pizzas`
-- -----------------------------------------------------
START TRANSACTION;
USE `pizzasevice`;
INSERT INTO `pizzaservice`.`pizzas` (`id`, `pizza_name`, `price`, `pizza_type`) VALUES (1, 'pizza1', 12.4, 'Meat');
INSERT INTO `pizzaservice`.`pizzas` (`id`, `pizza_name`, `price`, `pizza_type`) VALUES (2, 'pizza2', 24.4, 'Vegeterian');
INSERT INTO `pizzaservice`.`pizzas` (`id`, `pizza_name`, `price`, `pizza_type`) VALUES (3, 'pizza3', 22.5, 'Sea');

COMMIT;

